export const colors = {
	'transparent': 'transparent',
	'brand': 'var(--md-source-primary)',
	'primary': {
		DEFAULT: 'hsl(var(--md-sys-color-primary) / <alpha-value>)',
		container: 'var(--md-sys-color-primary-container)',
		0: 'var(--md-ref-palette-primary0)',
		10: 'var(--md-ref-palette-primary10)',
		20: 'var(--md-ref-palette-primary20)',
		25: 'var(--md-ref-palette-primary25)',
		30: 'var(--md-ref-palette-primary30)',
		35: 'var(--md-ref-palette-primary35)',
		40: 'var(--md-ref-palette-primary40)',
		50: 'var(--md-ref-palette-primary50)',
		60: 'var(--md-ref-palette-primary60)',
		70: 'var(--md-ref-palette-primary70)',
		80: 'var(--md-ref-palette-primary80)',
		90: 'var(--md-ref-palette-primary90)',
		95: 'var(--md-ref-palette-primary95)',
		98: 'var(--md-ref-palette-primary98)',
		99: 'var(--md-ref-palette-primary99)',
		100: 'var(--md-ref-palette-primary100)',
	},
	'on-primary': {
		DEFAULT: 'var(--md-sys-color-on-primary)',
		container: 'var(--md-sys-color-on-primary-container)',
	},
	'secondary': {
		DEFAULT: 'var(--md-sys-color-secondary)',
		container: 'var(--md-sys-color-secondary-container)',
		0: 'var(--md-ref-palette-secondary0)',
		10: 'var(--md-ref-palette-secondary10)',
		20: 'var(--md-ref-palette-secondary20)',
		25: 'var(--md-ref-palette-secondary25)',
		30: 'var(--md-ref-palette-secondary30)',
		35: 'var(--md-ref-palette-secondary35)',
		40: 'var(--md-ref-palette-secondary40)',
		50: 'var(--md-ref-palette-secondary50)',
		60: 'var(--md-ref-palette-secondary60)',
		70: 'var(--md-ref-palette-secondary70)',
		80: 'var(--md-ref-palette-secondary80)',
		90: 'var(--md-ref-palette-secondary90)',
		95: 'var(--md-ref-palette-secondary95)',
		98: 'var(--md-ref-palette-secondary98)',
		99: 'var(--md-ref-palette-secondary99)',
		100: 'var(--md-ref-palette-secondary100)',
	},
	'on-secondary': {
		DEFAULT: 'var(--md-sys-color-on-secondary)',
		container: 'var(--md-sys-color-on-secondary-container)',
	},
	'tertiary': {
		DEFAULT: 'var(--md-sys-color-tertiary)',
		container: 'var(--md-sys-color-tertiary-container)',
		0: 'var(--md-ref-palette-tertiary0)',
		10: 'var(--md-ref-palette-tertiary10)',
		20: 'var(--md-ref-palette-tertiary20)',
		25: 'var(--md-ref-palette-tertiary25)',
		30: 'var(--md-ref-palette-tertiary30)',
		35: 'var(--md-ref-palette-tertiary35)',
		40: 'var(--md-ref-palette-tertiary40)',
		50: 'var(--md-ref-palette-tertiary50)',
		60: 'var(--md-ref-palette-tertiary60)',
		70: 'var(--md-ref-palette-tertiary70)',
		80: 'var(--md-ref-palette-tertiary80)',
		90: 'var(--md-ref-palette-tertiary90)',
		95: 'var(--md-ref-palette-tertiary95)',
		98: 'var(--md-ref-palette-tertiary98)',
		99: 'var(--md-ref-palette-tertiary99)',
		100: 'var(--md-ref-palette-tertiary100)',
	},
	'on-tertiary': {
		DEFAULT: 'var(--md-sys-color-on-tertiary)',
		container: 'var(--md-sys-color-on-tertiary-container)',
	},
	'error': {
		DEFAULT: 'var(--md-sys-color-error)',
		container: 'var(--md-sys-color-error-container)',
		0: 'var(--md-ref-palette-error0)',
		10: 'var(--md-ref-palette-error10)',
		20: 'var(--md-ref-palette-error20)',
		25: 'var(--md-ref-palette-error25)',
		30: 'var(--md-ref-palette-error30)',
		35: 'var(--md-ref-palette-error35)',
		40: 'var(--md-ref-palette-error40)',
		50: 'var(--md-ref-palette-error50)',
		60: 'var(--md-ref-palette-error60)',
		70: 'var(--md-ref-palette-error70)',
		80: 'var(--md-ref-palette-error80)',
		90: 'var(--md-ref-palette-error90)',
		95: 'var(--md-ref-palette-error95)',
		98: 'var(--md-ref-palette-error98)',
		99: 'var(--md-ref-palette-error99)',
		100: 'var(--md-ref-palette-error100)',
	},
	'on-error': {
		DEFAULT: 'var(--md-sys-color-on-error)',
		container: 'var(--md-sys-color-on-error-container)',
	},
	'background': 'var(--md-sys-color-background)',
	'on-background': 'var(--md-sys-color-on-background)',
	'surface': {
		DEFAULT: 'var(--md-sys-color-surface)',
		dim: 'var(--md-sys-color-surface-dim)',
		bright: 'var(--md-sys-color-surface-bright)',
		container: {
			DEFAULT: 'var(--md-sys-color-surface-container)',
			lowest: 'var(--md-sys-color-surface-container-lowest)',
			low: 'var(--md-sys-color-surface-container-low)',
			high: 'var(--md-sys-color-surface-container-high)',
			highest: 'var(--md-sys-color-surface-container-highest)',
		},
		tint: 'var(--md-sys-color-surface-tint)',
	},
	'on-surface': {
		DEFAULT: 'hsl(var(--md-sys-color-on-surface) / <alpha-value>)',
		container: 'var(--md-sys-color-on-surface-container)',
	},
	'outline': {
		DEFAULT: 'var(--md-sys-color-outline)',
		variant: 'var(--md-sys-color-outline-variant)',
	},
	shadow: 'var(--md-sys-color-shadow)',
	neutral: {
		0: 'var(--md-ref-palette-neutral0)',
		10: 'var(--md-ref-palette-neutral10)',
		20: 'var(--md-ref-palette-neutral20)',
		25: 'var(--md-ref-palette-neutral25)',
		30: 'var(--md-ref-palette-neutral30)',
		35: 'var(--md-ref-palette-neutral35)',
		40: 'var(--md-ref-palette-neutral40)',
		50: 'var(--md-ref-palette-neutral50)',
		60: 'var(--md-ref-palette-neutral60)',
		70: 'var(--md-ref-palette-neutral70)',
		80: 'var(--md-ref-palette-neutral80)',
		90: 'var(--md-ref-palette-neutral90)',
		95: 'var(--md-ref-palette-neutral95)',
		98: 'var(--md-ref-palette-neutral98)',
		99: 'var(--md-ref-palette-neutral99)',
		100: 'var(--md-ref-palette-neutral100)',
		variant: {
			0: 'var(--md-ref-palette-neutral-variant0)',
			10: 'var(--md-ref-palette-neutral-variant10)',
			20: 'var(--md-ref-palette-neutral-variant20)',
			25: 'var(--md-ref-palette-neutral-variant25)',
			30: 'var(--md-ref-palette-neutral-variant30)',
			35: 'var(--md-ref-palette-neutral-variant35)',
			40: 'var(--md-ref-palette-neutral-variant40)',
			50: 'var(--md-ref-palette-neutral-variant50)',
			60: 'var(--md-ref-palette-neutral-variant60)',
			70: 'var(--md-ref-palette-neutral-variant70)',
			80: 'var(--md-ref-palette-neutral-variant80)',
			90: 'var(--md-ref-palette-neutral-variant90)',
			95: 'var(--md-ref-palette-neutral-variant95)',
			98: 'var(--md-ref-palette-neutral-variant98)',
			99: 'var(--md-ref-palette-neutral-variant99)',
			100: 'var(--md-ref-palette-neutral-variant100)',
		}
	}
};
