name: Run test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - name: install packages
        id: install-packages
        run: npm install

      - name: run test
        id: run-test
        run: npm run test
